//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesERP : DbContext
    {
        public EntitiesERP()
            : base("name=EntitiesERP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ALMACEN> TBL_ALMACEN { get; set; }
        public virtual DbSet<TBL_ARTICULO> TBL_ARTICULO { get; set; }
        public virtual DbSet<TBL_COMPANIA> TBL_COMPANIA { get; set; }
        public virtual DbSet<TBL_EXISTENCIA> TBL_EXISTENCIA { get; set; }
        public virtual DbSet<TBL_ROLE> TBL_ROLE { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
        public virtual DbSet<TBL_CATEGORIA_ARTICULO> TBL_CATEGORIA_ARTICULO { get; set; }
        public virtual DbSet<TBL_PROVEEDOR> TBL_PROVEEDOR { get; set; }
    }
}
