//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivosOrden
    {
        public int Id_ArchivosOrden { get; set; }
        public Nullable<int> Id_Orden { get; set; }
        public byte[] Archivo { get; set; }
        public string Nombre { get; set; }
        public string Extension { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
    }
}
