//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivosOrden
    {
        public int Id_ArchivosOrden { get; set; }
        public Nullable<int> Id_Orden { get; set; }
        public byte[] Archivo { get; set; }
        public string Nombre { get; set; }
        public string Extension { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
    }
}
