//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesDetalle
    {
        public int Id_OrdenDetalle { get; set; }
        public Nullable<int> Id_Orden { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<int> Id_EstatusOrden { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> EntregaParcial { get; set; }
        public string EntregarA { get; set; }
        public Nullable<System.DateTime> FechaActualizacionEstatus { get; set; }
    
        public virtual EstatusOrden EstatusOrden { get; set; }
        public virtual Ordenes Ordenes { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
