//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesDetalle
    {
        public int Id_OrdenDetalle { get; set; }
        public Nullable<int> Id_Orden { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<int> Id_EstatusOrden { get; set; }
        public string Cantidad { get; set; }
    
        public virtual ArchivosOrden ArchivosOrden { get; set; }
        public virtual EstatusOrden EstatusOrden { get; set; }
        public virtual Ordenes Ordenes { get; set; }
    }
}
