//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public int ID_ROL { get; set; }
        public int ID_COMPANIA { get; set; }
        public string NOMBRE { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
    
        public virtual TBL_COMPANIA TBL_COMPANIA { get; set; }
        public virtual TBL_ROLE TBL_ROLE { get; set; }
    }
}
