//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PROVEEDOR
    {
        public int ID_PROVEEDOR { get; set; }
        public int ID_COMPANIA { get; set; }
        public string NOMBRE { get; set; }
        public string RFC { get; set; }
        public string TELEFONO1 { get; set; }
        public string TELEFONO2 { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
    
        public virtual TBL_COMPANIA TBL_COMPANIA { get; set; }
    }
}
