//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLE_MOVIMIENTO_SALIDA_ALMACEN
    {
        public int ID_DETALLE_MOVIMIENTO_SALIDA_ALMACEN { get; set; }
        public int ID_MOVIMIENTO_SALIDA_ALMACEN { get; set; }
        public int ID_ARTICULO { get; set; }
        public decimal CANTIDAD { get; set; }
        public string CONDICION_ARTICULO_SALIDA { get; set; }
        public string CONDICION_ARTICULO_REGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_REGRESO { get; set; }
    
        public virtual TBL_ARTICULO TBL_ARTICULO { get; set; }
        public virtual TBL_MOVIMIENTO_SALIDA_ALMACEN TBL_MOVIMIENTO_SALIDA_ALMACEN { get; set; }
    }
}
