//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETAILS_VENTA
    {
        public int ID_DETAIL_VENTA { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<int> ID_ARTICULO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<double> PRECIO { get; set; }
    
        public virtual TBL_ARTICULO TBL_ARTICULO { get; set; }
        public virtual TBL_VENTA TBL_VENTA { get; set; }
    }
}
