//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETAILS_VENTA
    {
        public int ID_DETAIL_VENTA { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<int> ID_ARTICULO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<double> PRECIO { get; set; }
    
        public virtual TBL_ARTICULO TBL_ARTICULO { get; set; }
        public virtual TBL_VENTA TBL_VENTA { get; set; }
    }
}
