//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VENTA_PROMOTOR
    {
        public int ID_VENTA_PROMOTOR { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    
        public virtual TBL_VENTA TBL_VENTA { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
