//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ERP_BITACORA
    {
        public int ID_BITACORA { get; set; }
        public string USUARIO { get; set; }
        public string ACCION { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
    }
}
