//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ERP_CORTE_EXISTENCIA_ALMACEN
    {
        public int ID_CORTE_EXISTENCIA_ALMACEN { get; set; }
        public int ID_SEMANA { get; set; }
        public int ID_ALMACEN { get; set; }
        public int ID_ARTICULO { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual TBL_ALMACEN TBL_ALMACEN { get; set; }
        public virtual TBL_ARTICULO TBL_ARTICULO { get; set; }
        public virtual TBL_SEMANA TBL_SEMANA { get; set; }
    }
}
