//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SEMANA
    {
        public int ID_SEMANA { get; set; }
        public Nullable<int> NO_SEMANA { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<System.DateTime> DIA_INICIAL { get; set; }
        public Nullable<System.DateTime> DIA_FINAL { get; set; }
    }
}
