//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLE_MOVIMIENTO_ENTRADA_ALMACEN
    {
        public int ID_DETALLE_MOVIMIENTO_ENTRADA_ALMACEN { get; set; }
        public int ID_MOVIMIENTO_ENTRADA_ALMACEN { get; set; }
        public Nullable<int> ID_ARTICULO { get; set; }
        public Nullable<int> ID_UNIDAD { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
    
        public virtual TBL_ARTICULO TBL_ARTICULO { get; set; }
        public virtual TBL_UNIDAD TBL_UNIDAD { get; set; }
        public virtual TBL_MOVIMIENTO_ALMACEN TBL_MOVIMIENTO_ALMACEN { get; set; }
    }
}
