//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ALERTAS_STOCK_MIN
    {
        public int ID_ALERTA_STOCK_MIN { get; set; }
        public Nullable<int> ID_ARTICULO { get; set; }
        public Nullable<decimal> CANTIDAD_MINIMA { get; set; }
    
        public virtual TBL_ARTICULO TBL_ARTICULO { get; set; }
    }
}
