//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CATEGORIA_ARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CATEGORIA_ARTICULO()
        {
            this.TBL_ARTICULO = new HashSet<TBL_ARTICULO>();
        }
    
        public int ID_CATEGORIA_ARTICULO { get; set; }
        public Nullable<int> ID_COMPANIA { get; set; }
        public string NOMBRE_CATEGORIA { get; set; }
        public string NUM_CATEGORIA { get; set; }
    
        public virtual TBL_COMPANIA TBL_COMPANIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ARTICULO> TBL_ARTICULO { get; set; }
    }
}
