//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SEMANA
    {
        public int ID_SEMANA { get; set; }
        public Nullable<int> NO_SEMANA { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<System.DateTime> DIA_INICIAL { get; set; }
        public Nullable<System.DateTime> DIA_FINAL { get; set; }
    }
}
