//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ERP_BITACORA
    {
        public int ID_BITACORA { get; set; }
        public string USUARIO { get; set; }
        public string ACCION { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
    }
}
