//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ERP_PAGO_PLAN
    {
        public int ID_PAGO { get; set; }
        public Nullable<int> ID_COMPANIA { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public Nullable<double> MONTO { get; set; }
    
        public virtual TBL_COMPANIA TBL_COMPANIA { get; set; }
    }
}
