//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MOVIMIENTO_SALIDA_ALMACEN
    {
        public int ID_MOVIMIENTO_SALIDA_ALMACEN { get; set; }
        public int ID_ALMACEN { get; set; }
        public int ID_ARTICULO { get; set; }
        public string USUARIO_SOLICITO { get; set; }
        public decimal CANTIDAD { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public string CONDICION_ARTICULO_SALIDA { get; set; }
        public Nullable<System.DateTime> FECHA_REGRESO { get; set; }
        public string CONDICION_ARTICULO_REGRESO { get; set; }
        public bool CONSUMIBLE { get; set; }
        public string USUARIO_ATENDIO { get; set; }
    
        public virtual TBL_ALMACEN TBL_ALMACEN { get; set; }
        public virtual TBL_ARTICULO TBL_ARTICULO { get; set; }
    }
}
