//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ALERTAS_STOCK_MIN
    {
        public int ID_ALERTA_STOCK_MIN { get; set; }
        public int ID_ARTICULO { get; set; }
        public decimal CANTIDAD_MINIMA { get; set; }
    
        public virtual TBL_ARTICULO TBL_ARTICULO { get; set; }
    }
}
