//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEPOSITOS
    {
        public int ID_DEPOSITO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<double> MONTO { get; set; }
        public string BANCO { get; set; }
        public string DESCRIPCION { get; set; }
        public string URL_ARCHIVO { get; set; }
    
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
