//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ERP_PAGO_PLAN
    {
        public int ID_PAGO { get; set; }
        public Nullable<int> ID_COMPANIA { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public Nullable<double> MONTO { get; set; }
    
        public virtual TBL_COMPANIA TBL_COMPANIA { get; set; }
    }
}
