//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETAILS_ARTICULO
    {
        public int ID_DETAILS_ARTICULO { get; set; }
        public int ID_ARTICULO { get; set; }
        public double PRECIO_UNIDAD { get; set; }
        public double PRECIO_MASTER { get; set; }
        public double PRECIO_PROMOTOR { get; set; }
        public double PRECIO_GERENTE { get; set; }
    
        public virtual TBL_ARTICULO TBL_ARTICULO { get; set; }
    }
}
