//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MOVIMIENTO_SALIDA_ALMACEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MOVIMIENTO_SALIDA_ALMACEN()
        {
            this.TBL_DETALLE_MOVIMIENTO_SALIDA_ALMACEN = new HashSet<TBL_DETALLE_MOVIMIENTO_SALIDA_ALMACEN>();
        }
    
        public int ID_MOVIMIENTO_SALIDA_ALMACEN { get; set; }
        public int ID_ALMACEN { get; set; }
        public string FOLIO { get; set; }
        public string USUARIO_SOLICITO { get; set; }
        public System.DateTime FECHA_SALIDA { get; set; }
        public string USUARIO_ATENDIO { get; set; }
    
        public virtual TBL_ALMACEN TBL_ALMACEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLE_MOVIMIENTO_SALIDA_ALMACEN> TBL_DETALLE_MOVIMIENTO_SALIDA_ALMACEN { get; set; }
    }
}
