//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MOVIMIENTO_ALMACEN_INTERNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MOVIMIENTO_ALMACEN_INTERNO()
        {
            this.TBL_DETALLE_MOVIMIENTO_ALMACEN_INTERNO = new HashSet<TBL_DETALLE_MOVIMIENTO_ALMACEN_INTERNO>();
        }
    
        public int ID_MOVIMIENTO_ALMACEN_INTERNO { get; set; }
        public Nullable<int> ID_ALMACEN_ORIGEN { get; set; }
        public Nullable<int> ID_ALMACEN_DESTINO { get; set; }
        public string FOLIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual TBL_ALMACEN TBL_ALMACEN { get; set; }
        public virtual TBL_ALMACEN TBL_ALMACEN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLE_MOVIMIENTO_ALMACEN_INTERNO> TBL_DETALLE_MOVIMIENTO_ALMACEN_INTERNO { get; set; }
    }
}
